version: '3'
services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - C:\WebDev\Docker\blog-api\www:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network
  nginx:
    build:
      context: ./nginx
    volumes:
      - C:\WebDev\Docker\blog-api\www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8282:80"
      - "443:443"
    networks:
      - app-network
  db:
    build:
      context: ./database

    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/data/:/docker-entrypoint-initdb.d/
      - ./database/data/my.cnf:/etc/mysql/my.cnf
      - ./database/data/mysql:/var/lib/mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    networks:
      - app-network
    volumes:
      - /sessions
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local